### ISSUE TITLE
Namespace handling

### ISSUE THREAD

**Issue by mbtools** [SchwarzIT/sap-usi#2]
I just found your ABAP repositories. Nice work! You have one the a few open-source solutions I'm aware of that are using namespaces. I'm using them in [MBT](https://github.com/Marc-Bernard-Tools), too. 

Just a small correction to https://github.com/SchwarzIT/sap-usi/blob/main/docs/MAINTAIN_REPAIR_LICENSE.md. abapGit is able to deploy the namespace license key as well. It just has to be a two step process: First pull only the `NSPC` object, then all other objects. 😃 

I would love to hear more about your experience in this area. If you're interested in an informal chat, send me an email at marc(at)marcbernardtools.com. 

PS: Gerne auch in Deutsch

**Comment by NeumannJoerg** [comment]
I took that information from the [abapGit documentation](https://docs.abapgit.org/ref-namespaces.html). I just checked the documentation and it still says that namespaces must be created manually.
![abapGit​](https://user-images.githubusercontent.com/86975244/231453068-72f413ca-c775-41f1-b004-0dde5bf72e99.png)

I still tried to pull the ```NSPC``` object selectively like you suggested.

# TEST 1 - Package /MBTOOLS/TEST
Since the objects of the repository belong to the namespace /MBTOOLS/, the package has to belong to the same namespace. I tried to create the repository using the non-existent package /MBTOOLS/TEST.
![create_repo_01](https://user-images.githubusercontent.com/86975244/231476737-d5ce069a-c711-4f1f-a1b4-abfac38c05ce.png)

The online repo was created and I saw the following message.
![create_repo_02](https://user-images.githubusercontent.com/86975244/231477469-a16a58a7-6484-456d-a798-ca0bdc14ddf7.png)

I ignored that message and tried to selectively pull the ```NSPC``` object.
![create_repo_03](https://user-images.githubusercontent.com/86975244/231477905-da4f7abe-9f0b-4859-93c3-fb19a587be23.png)

I received the following message:
![create_repo_04](https://user-images.githubusercontent.com/86975244/231478105-7d65ec5a-764e-4dbc-9344-51fffa095984.png)
![create_repo_05](https://user-images.githubusercontent.com/86975244/231478148-4fc25b82-3b46-497c-93b8-732ed1c2f430.png)

# TEST 2 - Package ZTEST_NAMESPACE_DOWNLOAD
Since the first test did not work like expected I tried using a package from an already accessible namespace (Z*).
![create_repo_01](https://user-images.githubusercontent.com/86975244/231459712-d1391341-3be0-440d-8059-3c4eba082401.png)

The selective pull of the ```NSPC``` object worked this time and the change was recorded in a transport request.

But when I tried to clone the other objects from the repository, I got these error messages.
![create_repo_04](https://user-images.githubusercontent.com/86975244/231461237-dddaa9fd-9700-461b-96a0-d99551b841cc.png)

The error message in SE80 was a bit more specific:
![create_repo_05](https://user-images.githubusercontent.com/86975244/231461880-3b2358a1-2bd6-4ca6-bc2a-945635bc221e.png)

To make the pull work, I had to manually create a package in the /MBTOOLS/ namespace and use the database utility to overwrite the online repo's package assignment.

Am I making a mistake?

**Comment by mbtools** [comment]
Fixed by https://github.com/abapGit/abapGit/pull/6210 and https://github.com/abapGit/abapGit/pull/6212 😃

**Comment by NeumannJoerg** [comment]
Thanks for the update! https://github.com/abapGit/abapGit/pull/6210 has not been merged yet, but I'll keep an eye on it.

**Comment by NeumannJoerg** [comment]
I just re-tested https://github.com/abapGit/abapGit/pull/6210 and everything worked fine:
- I got an error message when using a package, that did not belong to the right namespace
- abapGit shows a message regarding the namespace and offers to pull it first
- pulling the namespace worked, as expected
- pulling objects from the repo after that worked as well

I updated our documentation accordingly.

Thank you for reaching out to us! 
We might have missed that new feature otherwise.
